apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
  namespace: openshift-lightspeed
type: Opaque
stringData:
  apitoken: "dummy-key"
---
apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
  namespace: openshift-lightspeed
spec:
  llm:
    providers:
      - name: openai
        type: openai
        url: "http://litellm.litellm.svc:80/v1"
        credentialsSecretRef:
          name: litellm-secret
        models:
          - name: gpt-4
  ols:
    defaultProvider: openai
    defaultModel: gpt-4
    introspectionEnabled: true
    logging:
      level: INFO
